REATE DATABASE base_restaurante
    DEFAULT CHARACTER SET = 'utf8mb4';

USE base_restaurante;

CREATE TABLE MESERO (
    Mes_id INT(10) PRIMARY KEY AUTO_INCREMENT,
    Mes_nombre VARCHAR(20)
);

CREATE TABLE TIPO_CLIENTE (
    TiC_id INT(10) PRIMARY KEY AUTO_INCREMENT,
    TiC_tipo VARCHAR(20)
);

CREATE TABLE TIPO_PRODUCTO (
    TiP_id INT(10) PRIMARY KEY AUTO_INCREMENT,
    TiP_nombre VARCHAR(20)
);

CREATE TABLE CATEGORIA_PRODUCTO (
    CaP_id INT(10) PRIMARY KEY AUTO_INCREMENT,
    CaP_nombre VARCHAR(20)
);

CREATE TABLE PRODUCTO (
    Prod_id INT(10) PRIMARY KEY AUTO_INCREMENT,
    Prod_nombre VARCHAR(20),
    Prod_costo INT(10),
    CaP_id INT(10),
    TiP_id INT(10), 
    FOREIGN KEY (CaP_id) REFERENCES CATEGORIA_PRODUCTO (CaP_id),
    FOREIGN KEY (TiP_id) REFERENCES TIPO_PRODUCTO (TiP_id) 
);

CREATE TABLE ORDEN (
    Ord_id INT(10) PRIMARY KEY AUTO_INCREMENT,
    Ord_fecha DATE,
    Ord_mesa VARCHAR(20),
    Mes_id INT(10),
    TiC_id INT(10),
    FOREIGN KEY (Mes_id) REFERENCES MESERO (Mes_id),
    FOREIGN KEY (TiC_id) REFERENCES TIPO_CLIENTE (TiC_id) 
);

CREATE TABLE PEDIDO (
    Ped_id INT(10) PRIMARY KEY AUTO_INCREMENT,
    Ord_id INT(10),
    Prod_id INT(10),
    Ped_precio INT(10),
    FOREIGN KEY (Ord_id) REFERENCES ORDEN (Ord_id),
    FOREIGN KEY (Prod_id) REFERENCES PRODUCTO (Prod_id)
);


